### ISSUE TITLE
winhttp callback handle error case

### ISSUE THREAD

**Issue by youyuanwu** [youyuanwu/winext#1]
Error is not yet handled in the callback:
https://github.com/youyuanwu/winasio/blob/3ec686202443e9cd9cc667f6943ca77754a84b9a/include/boost/winasio/winhttp/winhttp_asio.hpp#L131

Case `WINHTTP_CALLBACK_STATUS_REQUEST_ERROR`  needs to be added and callback needs to be invoked with error code.

**Comment by tracygooo** [comment]
Jinghua will take this
