### ISSUE TITLE
Migrate to http api version 2

### ISSUE THREAD

**Issue by youyuanwu** [youyuanwu/winext#5]
More details: https://learn.microsoft.com/en-us/windows/win32/http/versioning-in-http-2-0
* Migrate HttpAddUrl 
Currently winasio is using HttpAddUrl:
```
HTTPAPI_LINKAGE ULONG HttpAddUrl(
  [in] HANDLE RequestQueueHandle,
  [in] PCWSTR FullyQualifiedUrl,
       PVOID  Reserved
);
```
but https://learn.microsoft.com/en-us/windows/win32/api/http/nf-http-httpaddurl
says 
```
Starting with HTTP Server API Version 2.0, applications should call [HttpAddUrlToUrlGroup](https://learn.microsoft.com/en-us/windows/desktop/api/http/nf-http-httpaddurltourlgroup) to register a URL; HttpAddUrl should not be used.
```
* Migrate https://learn.microsoft.com/en-us/windows/win32/api/http/nf-http-httpcreatehttphandle to [HttpCreateRequestQueue](https://learn.microsoft.com/en-us/windows/desktop/api/http/nf-http-httpcreaterequestqueue)

**Comment by allenhan2** [comment]
Yue will work on this, and background info from Youyuan, https://learn.microsoft.com/en-us/windows/win32/http/http-server-api-version-2-0-reference

**Comment by youyuanwu** [comment]
#16 Closed.
